###CREATE ACCOUNT
POST http://localhost:3000/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "name": "Bello Bello",
    "email": "belloc@example.com",
    "phone": "09034028984",
    "role": "ADMIN",
    "password": "$Ao9oxxxxxxxxxx"
}

###LOGIN ACCOUNT
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "belloc@example.com",
    "password": "$Ao9oxxxxxxxxxx"
}

###LOGOUT ACCOUNT
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>
