### Add new property
POST http://localhost:3000/api/properties/create
Content-Type: multipart/form-data; boundary=----Boundary
Accept: application/json
Authorization: Bearer <token>

------Boundary
Content-Disposition: form-data; name="title"

Yalwawa House34
------Boundary
Content-Disposition: form-data; name="description"

Self contain a room, kitchen, toilet, and water in compound
------Boundary
Content-Disposition: form-data; name="type"

SELF_CONTAINED
------Boundary
Content-Disposition: form-data; name="amount"

80000
------Boundary
Content-Disposition: form-data; name="duration"

YEARLY
------Boundary
Content-Disposition: form-data; name="address"

layin gidan wanka, yalwawa
------Boundary
Content-Disposition: form-data; name="city"

Dutse
------Boundary
Content-Disposition: form-data; name="state"

Jigawa
------Boundary
Content-Disposition: form-data; name="country"

Nigeria
------Boundary
Content-Disposition: form-data; name="images"; filename="house1.jpg"
Content-Type: image/jpeg

< C:/Users/you/Pictures/house1.jpg
------Boundary
Content-Disposition: form-data; name="images"; filename="house2.jpg"
Content-Type: image/jpeg

< C:/Users/you/Pictures/house2.jpg
------Boundary
Content-Disposition: form-data; name="images"; filename="house3.jpg"
Content-Type: image/jpeg

< C:/Users/you/Pictures/house3.jpg
------Boundary
Content-Disposition: form-data; name="images"; filename="house4.jpg"
Content-Type: image/jpeg

< C:/Users/you/Pictures/house4.jpg
------Boundary--

###GET ALL PROPERTY
GET http://localhost:3000/api/properties
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>

###GET ALL PROPERTY FOR PUBLIC USER
GET http://localhost:3000/api/properties/all-available
Content-Type: application/json
Accept: application/json

###GET property
GET http://localhost:3000/api/properties/:id
Content-Type: application/json
Accept: application/json


###update property
PATCH http://localhost:3000/api/properties/:id
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>

{
  "title": "Yalwawa House6",
  "description": "Self contain a room, no kitchen, SHARED toilet, and water in compound",
  "type": "SINGLE_ROOM",
  "amount": 50000
}

###update property image
PATCH http://localhost:3000/api/properties/image/:id
Content-Type: multipart/form-data; boundary=----Boundary
Accept: application/json
Authorization: Bearer <token>

------Boundary
Content-Disposition: form-data; name="images"; filename="house1.jpg"
Content-Type: image/jpeg

< C:/Users/you/Pictures/house1.jpg
------Boundary--


###delete property
DELETE http://localhost:3000/api/properties/:id
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>