###GET USERS BY ADMIN
GET http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>


###GET USER BY ADMIN
GET http://localhost:3000/api/users/6c722e95-6aac-4b93-ae6e-2f42289e72cb
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>


###GET MY PROFILE
GET http://localhost:3000/api/users/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>


###CHANGE USER PASSWORD
PATCH http://localhost:3000/api/users/me/edit
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>

{
  "name": "bello yenyen"
}


###CHANGE USER PASSWORD
PATCH http://localhost:3000/api/users/me/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>

{
  "currentPassword": "xxxxxxxxx",
  "newPassword": "xxxxxxxxxxx"
}

###UPDATE ACCOUNT STATUS USER BY admin
DELETE http://localhost:3000/api/users/5a1b20d8-7e89-4789-b0ef-4f1992004da7
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>

{
    "status": "suspended"
}

###DELETE MY ACCOUNT BY USER 
DELETE http://localhost:3000/api/users/profile/delete-account
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>

###DELETE USER ACCOUNT BY admin
DELETE http://localhost:3000/api/users/5a1b20d8-7e89-4789-b0ef-4f1992004da7
Content-Type: application/json
Accept: application/json
Authorization: Bearer <token>